name: Build no DockerHub
on:
  push:
    branches:
      - main  

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar código
        uses: actions/checkout@v2

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login no DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir e enviar imagem Docker
        uses: docker/build-push-action@v2
        with:
          context: ./lab03_docker/
          push: true
          dockerfile: ./Dockerfile
          tags: sherman/webacademy:latest

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Fazendo deploy
        run: echo "Deploy realizado com sucesso!"
        